### ISSUE TITLE
Contact Center - new update - UI issue

### ISSUE THREAD

**Issue by junction1153** [nemerald-voip/fspbx#13]
The agents view is not properly aligned. the second column is off and needs a UI tweak to align it with the first column

**Comment by liam43231** [comment]
The latest update to the [contact center](https://www.mycountrymobile.com/) UI has introduced some issues that are affecting user experience. Specifically, users have reported difficulties navigating the new layout, with certain menus and buttons not responding as expected. This can hinder agent efficiency and overall workflow, leading to frustration.

**Comment by nemerald-voip** [comment]
> The latest update to the [contact center](https://www.mycountrymobile.com/) UI has introduced some issues that are affecting user experience. Specifically, users have reported difficulties navigating the new layout, with certain menus and buttons not responding as expected. This can hinder agent efficiency and overall workflow, leading to frustration.

@liam43231 Contact Center addon is a commercial addon. Our support is happy to help over a remote session if you are using it. Otherwise submit screenshots here and we will try to help.

**Comment by nemerald-voip** [comment]
@junction1153 Can you paste a screenshot here?

**Comment by nemerald-voip** [comment]
@junction1153, no need for a screenshot. This layout issue has been addressed in the last update

**Comment by Cristian-LigueAi** [comment]
Good morning @nemerald-voip  I installed FSX on a fusionpbx and cannot find or use the contact center. Do I need any updates or adjustments on my part? Thank you in advance.

**Comment by nemerald-voip** [comment]
@Cristian-LigueAi  
I'm happy to clarify this for you. 
FS PBX is an open-source project, but the Contact Center module is a premium module. You can email sales@stellarvoip.com to ask for a trial license and installation instructions. Otherwise you can use the old FusionPBX call center management. You will need to remove this line from /etc/nginx/sites-available/fspbx.conf file
       
```
        location = /app/call_center_active/call_center_queue.php {
                rewrite ^ https://$host/contact-center  permanent;
        }
```

```
        location ~* ^/app/call_center_active/call_center_active.php {
                return 301 https://$host/contact-center;
        }
```

and then reload configuration

**Comment by Cristian-LigueAi** [comment]
I sent the email requesting testing. I'll be waiting, thank you.

**Comment by nemerald-voip** [comment]
@Cristian-LigueAi We sent you a detailed response
