### ISSUE TITLE
Menu Item can't add group(s)

### ISSUE THREAD

**Issue by tellco-nor** [nemerald-voip/fspbx#23]
When editting a menu item, I am not able to add Groups. The drop-down list is blank. There are groups when I go to the Groups Menu.

![menu-item-groups](https://github.com/user-attachments/assets/798e71e2-0bd8-4ac1-b25b-68f314529c04)

Any idea what is wrong? Thanks.

**Comment by nemerald-voip** [comment]
I noticed that your menu is also missing on the original FusionPBX page. Both issues are likely due to missing settings for your user. Open /users page and make sure to select both Time Zone and Language. Then log out and log back in and try again.

**Comment by tellco-nor** [comment]
Thanks for the quick response. I was missing Time Zone. Now that is set, I'm still not seeing the orininal FusionPBX menu. It does show "Login" though.

**Comment by nemerald-voip** [comment]
The menu usually does not show because of one of those settings is missing. Does the user dropdown work now?

**Comment by tellco-nor** [comment]
got it working. is it suppose to ask me to login again when I go to pages that goes to the original FusionPBX?

thanks.

**Comment by nemerald-voip** [comment]
While it's not always the case, there is a possibility that the two sessions may expire at different times. You can adjust the timers to align them if needed. Additionally, revisiting older pages should become less frequent over time, as we continuously redesign then and improve the system. In fact, we recently added two new pages in the latest release.

For your reference, here is the link to the full list of newly added pages, which will continue to be updated regularly.

https://github.com/nemerald-voip/fspbx/wiki/List-of-all-redesigned-pages

**Comment by tellco-nor** [comment]
I'll look at adjusting the timers.

Is there an estaimte time for the IVR page?

Thanks.

**Comment by nemerald-voip** [comment]
We are prioritizing the development of the Time Conditions and IVR pages, with an expected delivery within the next two months. These two pages have been identified as the most challenging for end users, so we are focusing on improving them as quickly as possible.

Additionally, we anticipate that the Time Conditions feature will be integrated into the new Phone Numbers page, as this is the most logical location for making those adjustments.

Please let us know if you have any questions or further feedback.
