### ISSUE TITLE
Installation issue on debian 11

### ISSUE THREAD

**Issue by md-riaz** [nemerald-voip/fspbx#25]
System info:
-----------------------------
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

Error occured during command:  sh install.sh

-e Welcome to FS PBX installation script
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease
Ign:5 http://ppa.launchpad.net/ondrej/php/ubuntu oracular InRelease
Hit:6 https://packages.sury.org/php bullseye InRelease
Err:7 http://ppa.launchpad.net/ondrej/php/ubuntu oracular Release
  404  Not Found [IP: 185.125.190.80 80]
Hit:8 http://apt.postgresql.org/pub/repos/apt bullseye-pgdg InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu oracular Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
-e Error occurred during update and upgrade.

**Comment by md-riaz** [comment]
As the readme says, it's for debian 11/12,
Why is the installation code trying to use Ubuntu??

I think you should update the installation script to use the proper repository.

**Comment by nemerald-voip** [comment]
It's not the script that has an issue. It's your system trying to use Ubuntu repositories. I gave you instructions on how to try to mitigate this issue. if you open the script you will see that the very first thing it's doing is trying to update your system. 

`apt update && apt upgrade -y`

You can run those manually and you will probably get the same error. If you resolve the issue with the updates you should not have any issues to continue with the rest of the script.

**Comment by md-riaz** [comment]
Ok thanks,
Great work by the way👍

**Comment by nemerald-voip** [comment]
Thank you. I hope you enjoy it.
