### ISSUE TITLE
Issues Installing on Debian 12

### ISSUE THREAD

**Issue by jamesgoldston** [nemerald-voip/fspbx#26]
Hi, I am trying to get this installed on my test server, but it keeps throwing 419 | Page Expired after I try to log in. I followed the guide to get to this point, and the mail server is set up as well. I looked around to see if I can find the logs, but it doesn't seem to be producing logs.

**Comment by nemerald-voip** [comment]
419 error usually has to do with the session cookie.  Did you modify .env file? Specifically, the following entities
APP_URL and SESSION_DOMAIN. 
They should match; otherwise, the cookie doesn't get set correctly. 

Example:
```
APP_URL=https://your_domain.com
SESSION_DOMAIN=your_domain.com
```

Make sure to run after any changes in the .env file. 

`php artisan config:cache `

A good number of logs are written in this file if the above doesn't help. It can give us some ideas. 

`tail -f storage/logs/laravel.log `

**Comment by nemerald-voip** [comment]
And the APP_URL has to match the domain you use to access the app. So you should have 
`https://your_domain.com`
in your browser address bar.

I used an IP address instead of a domain name in the installation video. When you run the installation script, that's what gets written to the .env file.

**Comment by jamesgoldston** [comment]
I am still receiving that error and this is the log:

`#26 /var/www/fspbx/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#27 /var/www/fspbx/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#28 /var/www/fspbx/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#29 /var/www/fspbx/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#30 /var/www/fspbx/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#31 /var/www/fspbx/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#32 /var/www/fspbx/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#33 /var/www/fspbx/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#34 {main}
"}`

**Comment by nemerald-voip** [comment]
This is just a part of the last error trace. Lines from 26 to 34. Please post all lines. 
If you run the tail command before you try to log in, you will see the full trace.

**Comment by jamesgoldston** [comment]
This is all I have in the log.
`[2024-10-17 18:42:14] local.ERROR: Connection refused [tcp://127.0.0.1:6379] {"exception":"[object] (Predis\\Connection\\ConnectionException(code: 111): Connection refused [tcp://127.>
[stacktrace]
#0 /var/www/fspbx/vendor/predis/predis/src/Connection/StreamConnection.php(109): Predis\\Connection\\AbstractConnection->onConnectionError()
#1 /var/www/fspbx/vendor/predis/predis/src/Connection/StreamConnection.php(154): Predis\\Connection\\StreamConnection->createStreamSocket()
#2 /var/www/fspbx/vendor/predis/predis/src/Connection/StreamConnection.php(80): Predis\\Connection\\StreamConnection->tcpStreamInitializer()
#3 /var/www/fspbx/vendor/predis/predis/src/Connection/AbstractConnection.php(85): Predis\\Connection\\StreamConnection->createResource()
#4 /var/www/fspbx/vendor/predis/predis/src/Connection/StreamConnection.php(230): Predis\\Connection\\AbstractConnection->connect()
#5 /var/www/fspbx/vendor/predis/predis/src/Connection/AbstractConnection.php(169): Predis\\Connection\\StreamConnection->connect()
#6 /var/www/fspbx/vendor/predis/predis/src/Connection/StreamConnection.php(265): Predis\\Connection\\AbstractConnection->getResource()
#7 /var/www/fspbx/vendor/predis/predis/src/Connection/StreamConnection.php(372): Predis\\Connection\\StreamConnection->write()
#8 /var/www/fspbx/vendor/predis/predis/src/Connection/AbstractConnection.php(122): Predis\\Connection\\StreamConnection->writeRequest()
#9 /var/www/fspbx/vendor/predis/predis/src/Client.php(381): Predis\\Connection\\AbstractConnection->executeCommand()
#10 /var/www/fspbx/vendor/predis/predis/src/Client.php(336): Predis\\Client->executeCommand()
#11 /var/www/fspbx/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\\Client->__call()
#12 /var/www/fspbx/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(229): Illuminate\\Redis\\Connections\\Connection->command()
#13 /var/www/fspbx/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(39): Illuminate\\Redis\\Connections\\Connection->__call()
#14 /var/www/fspbx/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(50): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->names()
#15 /var/www/fspbx/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(99): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->all()
#16 /var/www/fspbx/vendor/laravel/horizon/src/MasterSupervisor.php(175): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->longestActiveTimeout()
#17 /var/www/fspbx/vendor/laravel/horizon/src/ListensForSignals.php(52): Laravel\\Horizon\\MasterSupervisor->terminate()
#18 /var/www/fspbx/vendor/laravel/horizon/src/MasterSupervisor.php(248): Laravel\\Horizon\\MasterSupervisor->processPendingSignals()
#19 /var/www/fspbx/vendor/laravel/horizon/src/MasterSupervisor.php(222): Laravel\\Horizon\\MasterSupervisor->loop()
#20 /var/www/fspbx/vendor/laravel/horizon/src/Console/HorizonCommand.php(56): Laravel\\Horizon\\MasterSupervisor->monitor()
#21 /var/www/fspbx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\HorizonCommand->handle()
#22 /var/www/fspbx/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /var/www/fspbx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#24 /var/www/fspbx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#25 /var/www/fspbx/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#26 /var/www/fspbx/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#27 /var/www/fspbx/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#28 /var/www/fspbx/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#29 /var/www/fspbx/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#30 /var/www/fspbx/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#31 /var/www/fspbx/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#32 /var/www/fspbx/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#33 /var/www/fspbx/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#34 {main}
"}`


Here is my .env file as well, domain is different, but is correct in my .env

`APP_NAME="FS PBX"
APP_ENV=local
#APP_ENV=production
APP_KEY=base64:/wCaEiWA6/bEaH4WXKdq8+t9CnFnS4tN04dxsk89qK4=
APP_DEBUG=true
#APP_DEBUG=true
APP_URL=https://mydomain.net

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=fusionpbx
DB_USERNAME=fusionpbx
DB_PASSWORD=DBPassword

SESSION_CONNECTION=pgsql

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DRIVER=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_DOMAIN=https://mydomain.net
SANCTUM_STATEFUL_DOMAINS=mydomain.net

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=live.smtp.mailtrap.io
MAIL_PORT=587
MAIL_USERNAME=smtp@mailtrap.io
MAIL_PASSWORD=MyPassword
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=noreply@mydomain.net
MAIL_FROM_NAME="MYDomain"
MAIL_REPLY_TO_ADDRESS=help@mydomain.net
MAIL_REPLY_TO_NAME="MyDomain"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

RINGOTEL_TOKEN=
RINGOTEL_API_URL=
RINGOTEL_URL=

THINQ_ACCOUNT_ID=
THINQ_USERNAME=
THINQ_TOKEN=
COMMIO_WEBHOOK_SECRET=

SINCH_AUTH_ID=
SINCH_API_KEY=
SINCH_MESSAGE_BROKER_URL=
SINCH_INBOUND_API_KEY=

POSTMARK_TOKEN=
POSTMARK_MESSAGE_STREAM_ID=

QUEUE_CONNECTION=redis
REDIS_CLIENT=predis

POLYCOM_LOG_DIRECTORY=

SLACK_FAX_HOOK=
SLACK_SMS_HOOK=
SLACK_SYSTEM_STATUS_HOOK=

CACHE_DRIVER=redis

OPENAI_API_KEY=

SANSAY_SERVER_1_URL=
SANSAY_SERVER_1_USER=
SANSAY_SERVER_1_API_KEY=
SANSAY_SERVER_2_URL=
SANSAY_SERVER_2_USER
SANSAY_SERVER_2_API_KEY=`

**Comment by nemerald-voip** [comment]
` Connection refused [tcp://127.0.0.1:6379]`
 This means that Redis is not running. 
 
 Verify by running 
 
` sudo systemctl status redis`

If Redis is not running, start it with:

`sudo systemctl start redis`

**Comment by jamesgoldston** [comment]
Redis is already running. Still nothing new in the logs when trying to sign in.

● redis-server.service - Advanced key-value store
     Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; preset:>
     Active: active (running) since Thu 2024-10-17 12:42:35 MDT; 4h 29min ago
       Docs: http://redis.io/documentation,
             man:redis-server(1)
   Main PID: 970 (redis-server)
     Status: "Ready to accept connections"
      Tasks: 5 (limit: 19129)
     Memory: 12.3M
        CPU: 1min 18.882s
     CGroup: /system.slice/redis-server.service
             └─970 "/usr/bin/redis-server 127.0.0.1:6379"

Oct 17 12:42:34 broadbyte.tel systemd[1]: Starting redis-server.service - Advan>
Oct 17 12:42:35 broadbyte.tel systemd[1]: Started redis-server.service - Advanc>

**Comment by nemerald-voip** [comment]
Oh, so that error wasn't the latest error. Ok, we are back to the session problem then. The session doesn't get set correctly. Would you like a remote session to get it sorted out?

**Comment by jamesgoldston** [comment]
No problem, shoot me an email at james@goldston.org and let me know of any cost.

Appreciate all the help.

**Comment by nemerald-voip** [comment]
I sent you an email

**Comment by nemerald-voip** [comment]
Someone else had the same issue and didn't have these settings in the .env file set to the same domain.

```
APP_URL=https://your_domain.com
SESSION_DOMAIN=your_domain.com
```

After setting them you always need to run

`php arsisan config:cache`

This resolves the 419 error when logging in.
