### ISSUE TITLE
Divison by zero issue on dashboard

### ISSUE THREAD

**Issue by md-riaz** [nemerald-voip/fspbx#27]
![image](https://github.com/user-attachments/assets/447ec079-20b4-46a0-96c4-4018d434dd5f)

**Comment by md-riaz** [comment]
Ok good, I just wanted to know another think is that, I saw fusionpbx code like extension update, it has some caching mechanism that is cleared on every changes, how did you handled that cache

**Comment by nemerald-voip** [comment]
FS PBX efficiently manages all cache updates, executing them as needed. The system now features a newly rewritten and optimized codebase to enhance performance and streamline the update process.

**Comment by md-riaz** [comment]
@nemerald-voip Hi,
I want share some suggestions, like disabling email challenge on login, as there is some usability issues.
For example if my fusionpbx doesnot have any email setup, then the email challenge works as expected but i don't get any mails, and I also don't know that email was not even sent or failed to sent etc.

This security should be optional and can be enabled from any setting page if anyone wanted.

**Comment by nemerald-voip** [comment]
Security is paramount today, so FS PBX was built with that in mind. But you can disable It by modifying this file 

`config/fortify.php`

update the config by commenting out email-challenge

```
    'features' => [
        // Features::registration(),
        Features::resetPasswords(),
        // Features::emailVerification(),
        Features::updateProfileInformation(),
        Features::updatePasswords(),
        Features::twoFactorAuthentication([
            'confirm' => true,
            'confirmPassword' => true,
            // 'window' => 5,
        ]),
        //'email-challenge',
        'remember-cookie',
    ],
```

**Comment by md-riaz** [comment]
Yap,, that is good, I would do it right away,
But make the email challenge after successful email sent, as this would not confuse that email sent or not
